# https://taskfile.dev
---
version: '3'

dotenv: [".env", "{{.ENV_FILE}}"]

vars:
  GRAPHS_DIR: graphs
  GRAPH_INTEGRATION: https://text2sparql.aksw.org/2025/corporate/
  PROJECTS_DIR: misc
  PROJECTS: >
    text2sparql-questions
  PACKAGES: >
    cmem-plugin-yaml

tasks:

  default:
    summary: Just a list of documented tasks.
    silent: true
    cmds:
      - task --list

  table:generate:
    desc: Generate the paper table
    cmds:
      - cmemc query execute ./misc/query-features-used.rq --accept text/csv

  images:generate:
    desc: Generate the paper images
    cmds:
      - >
        cmemc query execute ./misc/queries-per-property.rq --accept text/csv |
        misc/make_chart.py -o queries-per-property.svg
      - >
        cmemc query execute ./misc/queries-per-class.rq --accept text/csv |
        misc/make_chart.py -o queries-per-class.svg

  questions:list:
    desc: List all questions
    cmds:
      - >
        cat questions.yml |
        grep "en:" --color=always |
        grep -v "#" --color=always |
        less -r

  questions:update:
    desc: Update Corporate Memory with latest questions
    cmds:
      - cmemc dataset upload text2sparql-questions:questions-yml questions.yml
      - cmemc workflow execute text2sparql-questions:import-questions --wait

  clean:
    desc: Cleanup working directory
    cmds:
      - rm -f *.cpa misc/*.zip

  package:build:
    desc: Build the Package Archive
    cmds:
      - rm -f *.cpa misc/*.zip
      - cd misc; zip -9 -r text2sparql-questions.zip text2sparql-questions
      - cmemc package build . --replace --version {{.VERSION}}
    vars:
      VERSION:
        sh: git describe --always --dirty

  package:import:
    desc: Import the Package
    cmds:
      - task: clean
      - task: package:build
      - cmemc package install --replace --input *.cpa

